### ISSUE TITLE
Add html autocompletion

### ISSUE THREAD

**Issue by tajchumber** [jens1o/vscode-smarty#11]
Hi guys,

is it possible to add html autocompletion on this plugin?
This is a feature already present in the standard vscode for html.

![apr-10-2018 10-04-07](https://user-images.githubusercontent.com/16062635/38547317-b2bdf9a0-3ca6-11e8-8248-c5464d644968.gif)

or this possible to achieve via settings/configurations?

Thank you very much,
Taj

**Comment by jens1o** [comment]
Please search for duplicates, first. See #3. Is it planned to do so, but it may take some time to achieve this.
