### ISSUE TITLE
emmet support

### ISSUE THREAD

**Issue by webmasterMeyers** [jens1o/vscode-smarty#14]
I don't know anything about vs code extensions or I would attempt this code update myself.

To add html emmet to my .tpl files, I had to add this code to my User Settings
```
    "emmet.includeLanguages": {
      "smarty": "html"
    }

```
is it possible to make this default?  Thanks for this extension too!

**Comment by jens1o** [comment]
Thanks for your interest.

Well, it is part of a bigger progress as explained in the readme:
`This is planned as an 'out of the box' feature, but it may take some time to achieve.`

I/We/Whatever want to create a language server to provide better experience. This will be obsolete once #15 has been implemented.

Personally, I'd not use an extension that randomly changes my settings. Is it really worth it? Perhaps we should show a popup to ask the user after installing whether to automatically enable Emmet support.

Thoughts?

**Comment by webmasterMeyers** [comment]
fair enough.  I'd just leave it then.  I thought it might be a simple addition to the plugins settings.  Maybe a short note on the plugin page is all you would need.  I figured it out in about 30 minutes of messing around.
