### ISSUE TITLE
Is it possible to use *.htm file extension instead of *.tpl?

### ISSUE THREAD

**Issue by Dawid-Ohia** [jens1o/vscode-smarty#20]
I use *.htm extension for Smarty templates files. Is it possible to configure this extension to identify *.htm files as Smarty templates?

**Comment by arvislacis** [comment]
I personally add the following lines in my VSCode Workspace settings for every project which uses Smarty template engine and uses .htm,.html files for templates:

```
{
    "files.associations": {
        "*.html": "smarty",
        "*.htm": "smarty"
    }
}
```

**Comment by Dawid-Ohia** [comment]
@arvislacis Thanks! it works.
