### ISSUE TITLE
remove Character \

### ISSUE THREAD

**Issue by hoangnamitc** [jens1o/vscode-smarty#6]
How to remove character \ in

\{if condition}
 \{/if}

thanks

**Comment by g8up** [comment]
I got a solution:
- open `.vscode\extensions\imperez.smarty-0.2.0\snippets\snippets.json` under your install path ( under windows `%USERPROFILE%\.vscode`)
- change the property `if` (refer:https://github.com/imperez/vscode-smarty/blob/master/snippets/snippets.json#L74) to:
```
	"if": {
		"prefix": "if",
		"body": "\n{if $1}\n\t$0\n{/if}\n",
		"description": "",
		"scope": "text.html.smarty,source.smarty"
	},
```
- reload your smarty extension

**Comment by hoangnamitc** [comment]
Thanks you !
