### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by mcdado** [jens1o/vscode-smarty#9]
Hi, I'd like to improve this, but rather then fork it and use it on my own, I'd like to contribute back so that the install base of the extension can use it. Before doing that, I'd like to know that there's still somebody on the other end interested in this. 😄

**Comment by jens1o** [comment]
Unfortunately, it isn't maintained :/

**Comment by IsaiChristian** [comment]
Is there something similar? I use smarty pretty much every day

**Comment by jens1o** [comment]
@IsaiChristian I'm looking for something similar, too. Perhaps someone is able to fork it?

**Comment by imperez** [comment]
Oh wow sorry I haven't been getting emails from github so I had no idea there were conversations going on here. 

Sadly I don't have time to maintain this project. I would be more than willing to transfer ownership of the extension and this repo if someone is up for it?

**Comment by jens1o** [comment]
@imperez I could do that. I want to dig deeper in with vscode extensions. For example, I'm in the team of vscode-icons, and I'm active in the communities in php-intellisense and I'm a collaborator in the OneDark-Pro team. :)

**Comment by imperez** [comment]
Hi @jens1o I've put in a request to transfer ownership of this repo to you. As for the extension I need an email associated to the Visual Studio Marketplace. Can you make one [here](https://marketplace.visualstudio.com) and then I can make you an owner of the extension.

**Comment by jens1o** [comment]
@imperez Where can I see the request? I'd like to approve it, but I didn't found any notification. My Microsoft affiliated email is `jens-hausdorf-laptop@hotmail.de`.

**Comment by imperez** [comment]
@jens1o I've added you as an owner for the extension. You should be getting an email from GitHub to take over ownership of this repo. Let me know if you haven't gotten it yet.

**Comment by jens1o** [comment]
Got it. The repository is now moving. I've received both the Visual Studio Marketplace access and the GitHub transfer request.
![image](https://user-images.githubusercontent.com/11234139/38250802-021d1d84-3750-11e8-9019-25df84e2a8cf.png)

Thank you for supporting me!

**Comment by jens1o** [comment]
@imperez I'm not able to create an access token, because I couldn't find the page. Could you give me the link to it? For the `0.3.0` release, I needed to manually upload the package.

**Comment by imperez** [comment]
hey @jens1o check out this url that should have the steps you need to create the token.

https://docs.microsoft.com/en-us/vsts/integrate/get-started/authentication/pats?view=vsts

**Comment by jens1o** [comment]
@imperez Thanks, that was the link I was looking for. Just set it up.
